services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./docker/images/n8n/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "beso"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "682015"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://n8n.onrender.com" # هذا placeholder فقط
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
